name: Deploy to AWS Cloudformation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nodejs and npm
        run: sudo apt install nodejs npm -y
      
      - name: Install AWS CDK
        run: npm i -g aws-cdk
        
      - name: Install pip requirements
        run: pip install -r requirements.txt
        
      - name: CDK Deploy
        run: cdk deploy -f
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
